port: 7880
rtc:
  udp_port: 7881
  tcp_port: 7882

keys:
  LIVEKIT_URL : "wss://test-0xsooiuu.livekit.cloud"
  LIVEKIT_API_KEY : "APIiRSWjzSsmTXq"
  LIVEKIT_API_SECRET : "jSrWT2YS5QdBRVd5pkcKD9DiQ1TKARcBMejsTtj20e6"